### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by TechStudent10**
Fixed Typo in workflow

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
I just copied template from other repo, my bad lol

**Comment by TechStudent10** [comment]
Haha it's fine.

**Comment by KendallDoesCoding** [comment]
Actually, when I did it, it was correct but then Adarsh re-set it up. There
was no need of re-setting it up bro only token needed to be updated LOL,
but no worries :)

**Comment by TechStudent10** [comment]
@KendallDoesCoding your comments are being marked as spam.

**Pull request merged**
